# Generated by Django 5.2.4 on 2025-08-21 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstructura',
            fields=[
                ('codigo', models.CharField(choices=[('EXPANSION', 'Expansión'), ('REPOSICION_NUEVO', 'Reposición Nuevo'), ('REPOSICION_BAJO', 'Reposición Bajo')], max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Estructura',
                'verbose_name_plural': 'Tipos de Estructura',
            },
        ),
        migrations.CreateModel(
            name='ProcesoEstructura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_excel', models.FileField(upload_to='uploads/excel/')),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('PROCESANDO', 'Procesando'), ('COMPLETANDO_DATOS', 'Completando Datos'), ('GENERANDO_ARCHIVOS', 'Generando Archivos'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='INICIADO', max_length=20)),
                ('circuito', models.CharField(blank=True, max_length=100)),
                ('registros_totales', models.IntegerField(default=0)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_estructura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estructuras.tipoestructura')),
            ],
            options={
                'verbose_name': 'Proceso de Estructura',
                'verbose_name_plural': 'Procesos de Estructuras',
                'ordering': ['-created_at'],
            },
        ),
    ]
