# Generated by Django 5.2.4 on 2025-08-21 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoestructura',
            name='tipo_estructura',
            field=models.CharField(choices=[('EXPANSION', 'Expansión'), ('REPOSICION_NUEVO', 'Reposición Nuevo'), ('REPOSICION_BAJO', 'Reposición Bajo')], max_length=50),
        ),
        migrations.CreateModel(
            name='RegistroEstructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.IntegerField()),
                ('datos_originales', models.JSONField()),
                ('datos_procesados', models.JSONField()),
                ('datos_norma', models.JSONField()),
                ('tiene_errores', models.BooleanField(default=False)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='estructuras.procesoestructura')),
            ],
            options={
                'verbose_name': 'Registro de Estructura',
                'verbose_name_plural': 'Registros de Estructuras',
                'ordering': ['numero_fila'],
            },
        ),
        migrations.DeleteModel(
            name='TipoEstructura',
        ),
    ]
