# Generated by Django 5.2.4 on 2025-08-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0002_alter_procesoestructura_tipo_estructura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoestructura',
            name='campos_faltantes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='procesoestructura',
            name='datos_excel',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='procesoestructura',
            name='datos_norma',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='RegistroEstructura',
        ),
    ]
