# Generated by Django 5.2.4 on 2025-08-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0003_procesoestructura_campos_faltantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoestructura',
            name='archivos_generados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
