# Generated by Django 5.2.4 on 2025-08-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0004_procesoestructura_archivos_generados'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoestructura',
            name='estadisticas_clasificacion',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
