# Generated by Django 5.2.4 on 2025-08-22 15:41

from django.db import migrations


def fix_null_estadisticas(apps, schema_editor):
    """Corrige los registros que tienen NULL en estadisticas_clasificacion"""
    ProcesoEstructura = apps.get_model('estructuras', 'ProcesoEstructura')
    
    # Actualizar todos los registros que tienen NULL
    ProcesoEstructura.objects.filter(estadisticas_clasificacion__isnull=True).update(
        estadisticas_clasificacion={}
    )


def reverse_fix_null_estadisticas(apps, schema_editor):
    """Operación reversa - no hacer nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0005_procesoestructura_estadisticas_clasificacion'),
    ]

    operations = [
        migrations.RunPython(fix_null_estadisticas, reverse_fix_null_estadisticas),
    ]
