# Generated by Django 5.2.4 on 2025-08-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0006_auto_20250822_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoestructura',
            name='propietario_definido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='procesoestructura',
            name='requiere_definir_propietario',
            field=models.BooleanField(default=False),
        ),
    ]
