# Generated by Django 5.2.4 on 2025-08-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0007_procesoestructura_propietario_definido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoestructura',
            name='estado_salud_definido',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], help_text='Estado de salud definido por el usuario para todas las estructuras', max_length=20, null=True),
        ),
    ]
