# Generated by Django 5.2.4 on 2025-08-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0008_add_estado_salud_definido'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoestructura',
            name='estado_estructura_definido',
            field=models.CharField(blank=True, choices=[('CONSTRUCCION', 'Construcción'), ('RETIRADO', 'Retirado'), ('OPERACION', 'Operación')], help_text='Estado de estructura definido por el usuario para todas las estructuras', max_length=20, null=True),
        ),
    ]
