# Generated by Django 5.2.4 on 2025-08-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0009_add_estado_estructura_definido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesoestructura',
            name='tipo_estructura',
        ),
        migrations.AddField(
            model_name='procesoestructura',
            name='ajustes_clasificacion',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='procesoestructura',
            name='clasificacion_automatica',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='procesoestructura',
            name='clasificacion_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procesoestructura',
            name='total_desmantelado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procesoestructura',
            name='total_expansion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procesoestructura',
            name='total_reposicion_bajo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procesoestructura',
            name='total_reposicion_nuevo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='procesoestructura',
            name='estado',
            field=models.CharField(choices=[('INICIADO', 'Iniciado'), ('CLASIFICANDO', 'Clasificando Automáticamente'), ('CLASIFICADO', 'Clasificado para Revisión'), ('PROCESANDO', 'Procesando'), ('COMPLETANDO_DATOS', 'Completando Datos'), ('GENERANDO_ARCHIVOS', 'Generando Archivos'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='INICIADO', max_length=20),
        ),
    ]
